### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by SeeVetri** [shahshubh/Chatify#3]
May i know how to create config file and what to put inside it

**Comment by shahshubh** [comment]
in configs.dart you need to add these 3 

APP_ID = _[Agora.io APP ID after creating a project on their website](https://console.agora.io/)_
GIPHY_API_KEY = _[Giphy api key](https://developers.giphy.com/)_
FCM_SERVER_KEY = _[Your firebase fcm server key for push notifications](https://console.firebase.google.com/)_

```
const String APP_ID = "your-key"; 
const String GIPHY_API_KEY =  "your-key";
const String FCM_SERVER_KEY = "your-key";
```
