### ISSUE TITLE
Unimplemented Error on press search button keyboard

### ISSUE THREAD

**Issue by lohnsonok** [shahshubh/Chatify#5]
![Screenshot_20210623-160738](https://user-images.githubusercontent.com/60504466/123122480-f7c66500-d43d-11eb-93b7-b1c3fab0d5d2.png)

![Screenshot_20210623-160744](https://user-images.githubusercontent.com/60504466/123122506-fc8b1900-d43d-11eb-95e2-9d786edcbfa3.png)

**Comment by shahshubh** [comment]
Yes, that's because of [here](https://github.com/shahshubh/Chatify/blob/master/lib/screens/Chats/UserList.dart#L152) on Line 152 buildResults method. You can change the method accordingly or just copy the buildSuggestions() method logic and it should work.

**Comment by lohnsonok** [comment]
Thank you for answer. Yeah the method was found
